spring.application.name=gitTrainer
server.port=8081
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/git_trainer}
spring.datasource.username=${POSTGRES_USER:git_trainer}
spring.datasource.password=${POSTGRES_PASSWORD:git_trainer}
spring.datasource.driver-class-name=org.postgresql.Driver
