CREATE TABLE training_sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    scenario_slug VARCHAR(255) NOT NULL,
    scenario_title VARCHAR(512) NOT NULL,
    scenario_source VARCHAR(255) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    state VARCHAR(64) NOT NULL,
    submission_count INTEGER NOT NULL,
    consecutive_failure_count INTEGER NOT NULL,
    last_submission_id VARCHAR(128)
);

CREATE TABLE scenario_progress (
    scenario_slug VARCHAR(255) PRIMARY KEY,
    scenario_title VARCHAR(512) NOT NULL,
    scenario_source VARCHAR(255) NOT NULL,
    first_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_submitted_at TIMESTAMP WITH TIME ZONE,
    last_session_id VARCHAR(128) NOT NULL,
    last_submission_id VARCHAR(128),
    last_correctness VARCHAR(64),
    attempt_count INTEGER NOT NULL,
    completion_count INTEGER NOT NULL,
    last_completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE scenario_completion_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_slug VARCHAR(255) NOT NULL,
    scenario_title VARCHAR(512) NOT NULL,
    scenario_source VARCHAR(255) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    submission_id VARCHAR(128) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_scenario_completion_events_completed_at
    ON scenario_completion_events (completed_at DESC);
