CREATE TABLE authored_scenarios (
    scenario_slug VARCHAR(255) PRIMARY KEY,
    scenario_id VARCHAR(255) NOT NULL,
    source_key VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    title VARCHAR(512) NOT NULL,
    summary TEXT NOT NULL,
    difficulty VARCHAR(64) NOT NULL,
    tags_json JSONB NOT NULL,
    task_payload JSONB NOT NULL,
    repository_context_payload JSONB NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_authored_scenarios_source_key
    ON authored_scenarios (source_key)
    WHERE enabled = TRUE;

CREATE TABLE authored_scenario_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_slug VARCHAR(255) NOT NULL REFERENCES authored_scenarios (scenario_slug) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    answer_type VARCHAR(64) NOT NULL,
    raw_answer_value TEXT NOT NULL,
    normalized_answer_value TEXT NOT NULL,
    outcome_correctness VARCHAR(64) NOT NULL,
    outcome_code VARCHAR(128) NOT NULL,
    outcome_message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (scenario_slug, position),
    UNIQUE (scenario_slug, answer_type, normalized_answer_value)
);

CREATE INDEX idx_authored_scenario_answers_lookup
    ON authored_scenario_answers (scenario_slug, answer_type, normalized_answer_value);
