CREATE TABLE authored_scenario_validator_specs (
    validator_spec_id VARCHAR(255) PRIMARY KEY,
    scenario_slug VARCHAR(255) NOT NULL REFERENCES authored_scenarios (scenario_slug) ON DELETE CASCADE,
    answer_type VARCHAR(64) NOT NULL,
    validator_type VARCHAR(64) NOT NULL,
    timeout_ms INTEGER NOT NULL DEFAULT 5000,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (scenario_slug, answer_type)
);

CREATE INDEX idx_authored_scenario_validator_specs_lookup
    ON authored_scenario_validator_specs (scenario_slug, answer_type)
    WHERE enabled = TRUE;

CREATE TABLE authored_scenario_validator_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validator_spec_id VARCHAR(255) NOT NULL REFERENCES authored_scenario_validator_specs (validator_spec_id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    match_type VARCHAR(64) NOT NULL,
    raw_match_value TEXT NOT NULL,
    normalized_match_value TEXT NOT NULL,
    outcome_correctness VARCHAR(64) NOT NULL,
    outcome_code VARCHAR(128) NOT NULL,
    outcome_message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (validator_spec_id, position),
    UNIQUE (validator_spec_id, normalized_match_value)
);

CREATE INDEX idx_authored_scenario_validator_rules_lookup
    ON authored_scenario_validator_rules (validator_spec_id, normalized_match_value);

INSERT INTO authored_scenario_validator_specs (
    validator_spec_id,
    scenario_slug,
    answer_type,
    validator_type,
    timeout_ms,
    enabled
)
SELECT 'default:' || scenario_slug || ':' || answer_type,
       scenario_slug,
       answer_type,
       'exact_command_match',
       5000,
       TRUE
FROM authored_scenario_answers
GROUP BY scenario_slug, answer_type
ON CONFLICT (scenario_slug, answer_type) DO NOTHING;

INSERT INTO authored_scenario_validator_rules (
    validator_spec_id,
    position,
    match_type,
    raw_match_value,
    normalized_match_value,
    outcome_correctness,
    outcome_code,
    outcome_message
)
SELECT 'default:' || scenario_slug || ':' || answer_type,
       position,
       'exact_normalized_command',
       raw_answer_value,
       normalized_answer_value,
       outcome_correctness,
       outcome_code,
       outcome_message
FROM authored_scenario_answers
ON CONFLICT (validator_spec_id, normalized_match_value) DO NOTHING;
