-- Generated from scenario seed data.
DELETE FROM retry_feedback_templates;
DELETE FROM authored_scenarios;

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('status-basics', 'status-basics', 'default', 'db-seeded', 'Проверь изменения перед первым Git-действием', 'В `main` уже изменены `README.md` и `src/main.js`, а `notes/status-checklist.md` ещё не отслеживается. Сначала покажи короткий статус, а не меняй репозиторий.', 'BEGINNER', '["status","working-tree","basics"]'::jsonb, '{"status":"db-seeded","goal":"Вы на `main`. Перед любым `add`, `checkout` или очисткой нужно коротко проверить, какие файлы уже изменены и какие ещё не отслеживаются.","instructions":[{"position":1,"id":"inspect-working-tree-first","text":"Не меняйте репозиторий. Первый ответ должен быть командой чтения статуса."},{"position":2,"id":"confirm-short-status-signals","text":"Используйте короткий формат, чтобы сразу увидеть `README.md`, `src/main.js` и новый `notes/status-checklist.md`."},{"position":3,"id":"avoid-mutation-commands","text":"Ожидается безопасный следующий шаг из семейства `git status`, без stage, checkout и cleanup."}],"steps":[{"position":1,"title":"Заметьте, что вы уже на `main`","detail":"Переключать ветки не нужно. Сначала разберитесь с текущим рабочим деревом."},{"position":2,"title":"Подтвердите изменённые tracked-файлы","detail":"Команда должна показать, что `README.md` и `src/main.js` уже изменены."},{"position":3,"title":"Не забудьте про новый файл","detail":"`notes/status-checklist.md` пока не отслеживается и тоже должен попасть в обзор."},{"position":4,"title":"Выберите компактный вывод","detail":"Для этой задачи нужен короткий status, а не длинное описание состояния."},{"position":5,"title":"Оставьте репозиторий без изменений","detail":"После ответа рабочее дерево должно остаться в том же состоянии: задача только про проверку."}],"annotations":[{"position":1,"label":"Что нужно увидеть","message":"В рабочем дереве сейчас два modified-файла и один untracked-файл."},{"position":2,"label":"Какой шаг ожидается","message":"Правильный ответ — короткий `git status`, который ничего не меняет в репозитории."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"main","current":true},{"name":"docs/review-notes","current":false}],"commits":[{"id":"a1c9e31","summary":"docs: добавить черновик заметок по ревью"},{"id":"f72ab44","summary":"app: удержать оболочку рабочего пространства стабильной"}],"files":[{"path":"README.md","status":"modified"},{"path":"notes/status-checklist.md","status":"untracked"},{"path":"src/main.js","status":"modified"}],"annotations":[{"label":"Сигнал рабочего дерева","message":"`README.md` и `src/main.js` уже изменены, а `notes/status-checklist.md` ещё не добавлен в Git."},{"label":"Почему нельзя спешить","message":"До проверки статуса любой `git add`, `checkout` или очистка будет действием вслепую."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('branch-safety', 'branch-safety', 'default', 'db-seeded', 'Подтверди ветку и незавершённый hotfix', 'Вы уже на `release/hotfix-7`, а `src/ui/header.css` и `docs/release-checklist.md` изменены. Сначала подтвердите ветку и только потом решайте, можно ли переключаться.', 'BEGINNER', '["branching","navigation","basics"]'::jsonb, '{"status":"db-seeded","goal":"Перед любым `checkout` нужно подтвердить, что работа уже открыта в `release/hotfix-7`, и собрать branch-aware status незавершённых правок.","instructions":[{"position":1,"id":"confirm-active-branch-before-switching","text":"Сначала покажите, какая ветка активна сейчас. Без этого решение о переключении будет догадкой."},{"position":2,"id":"connect-open-edits-to-branch-purpose","text":"Свяжите `release/hotfix-7` с уже изменёнными `src/ui/header.css` и `docs/release-checklist.md`."},{"position":3,"id":"keep-next-step-observable","text":"Задача заканчивается на безопасной проверке branch-контекста. Делать `checkout` здесь ещё не нужно."}],"steps":[{"position":1,"title":"Подтвердите активную ветку","detail":"Первым шагом явно покажите, что работа уже открыта в `release/hotfix-7`."},{"position":2,"title":"Сопоставьте ветку с изменёнными файлами","detail":"`src/ui/header.css` и `docs/release-checklist.md` выглядят как незавершённый hotfix-контекст, а не новая feature-задача."},{"position":3,"title":"Соберите branch-aware status","detail":"Нужна короткая команда, которая показывает и ветку, и незавершённые изменения."},{"position":4,"title":"Оставьте переключение на потом","detail":"После такой проверки уже можно будет обсуждать `checkout`, но этот сценарий завершается раньше."}],"annotations":[{"position":1,"label":"Что проверяем","message":"Сначала подтверждаем активную ветку, потом убеждаемся, что в ней уже есть незавершённый hotfix."},{"position":2,"label":"Какой шаг ожидается","message":"Сценарий ведёт к branch-aware status, но только после явного подтверждения текущей ветки."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"release/hotfix-7","current":true},{"name":"feature/menu-refresh","current":false},{"name":"main","current":false}],"commits":[{"id":"b74e2d0","summary":"hotfix: восстановить отступы заголовка"},{"id":"197a0f4","summary":"release: отметить чеклист выкладки"}],"files":[{"path":"src/ui/header.css","status":"modified"},{"path":"docs/release-checklist.md","status":"modified"}],"annotations":[{"label":"Что видно в репозитории","message":"Сейчас активна `release/hotfix-7`, и оба изменённых файла выглядят как незавершённая release-работа."},{"label":"Почему нельзя переключаться сразу","message":"Пока вы не подтвердили текущую ветку и не увидели изменения рядом с ней, любой `checkout` смешивает hotfix и feature-контекст."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('history-cleanup-preview', 'history-cleanup-preview', 'default', 'db-seeded', 'Собери preview истории перед cleanup', 'В `feature/history-cleanup` наверху лежат `fixup!` и WIP-коммиты. Сначала покажи компактный граф истории, а не запускай `rebase -i`.', 'INTERMEDIATE', '["history","cleanup","planning"]'::jsonb, '{"status":"db-seeded","goal":"Нужно безопасно посмотреть верхушку истории и увидеть, какие коммиты пойдут в cleanup, не переписывая их.","instructions":[{"position":1,"id":"preview-commit-graph-before-rewrite","text":"Оставайтесь в режиме просмотра. Никакого `rebase`, `reset` или `commit --amend`."},{"position":2,"id":"use-fixup-and-wip-as-cues","text":"Команда должна явно показать `fixup!` и WIP рядом с основными коммитами, чтобы было видно будущий cleanup."},{"position":3,"id":"keep-next-step-in-preview-mode","text":"Лучший следующий шаг — компактный `git log` с графом и декорациями, без переписывания истории."}],"steps":[{"position":1,"title":"Посмотрите на верхушку ветки","detail":"Нужно увидеть последние коммиты в `feature/history-cleanup`, а не сразу планировать `rebase -i`."},{"position":2,"title":"Найдите `fixup!` и WIP-сигналы","detail":"Именно эти коммиты подсказывают, какие части истории ещё надо будет уплотнить."},{"position":3,"title":"Соберите компактный граф","detail":"Выберите такой `git log`, который показывает форму стека и декорации веток в одном выводе."},{"position":4,"title":"Не переписывайте историю раньше времени","detail":"Сценарий заканчивается на preview. Переписывание коммитов остаётся следующим, но не текущим шагом."},{"position":5,"title":"Сформулируйте основу для cleanup","detail":"После preview должно быть понятно, какие коммиты вы бы потом склеивали или переставляли."}],"annotations":[{"position":1,"label":"Что нужно увидеть","message":"В истории уже видны `fixup!` и WIP-коммиты, поэтому сначала нужен понятный preview графа."},{"position":2,"label":"Какой шаг ожидается","message":"Правильный ответ — команда из семейства `git log`, которая ничего не меняет, но показывает форму истории."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"feature/history-cleanup","current":true},{"name":"main","current":false}],"commits":[{"id":"c102d6b","summary":"fixup! ui: переименовать бейдж оболочки"},{"id":"91fe2ad","summary":"ui: переименовать бейдж оболочки"},{"id":"43bc8c1","summary":"wip: ещё раз подправить отступы"}],"files":[{"path":"frontend/src/styles.css","status":"modified"},{"path":"frontend/src/workspace-shell/view.js","status":"modified"}],"annotations":[{"label":"Сигнал для cleanup","message":"`fixup!` рядом с основным UI-коммитом и отдельный WIP уже показывают, что история просит аккуратного просмотра."},{"label":"Почему rebase пока рано","message":"Пока вы не увидели стек в компактном графе, любой `rebase -i` скрывает обязательный шаг анализа."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('remote-sync-preview', 'remote-sync-preview', 'default', 'db-seeded', 'Сначала обнови `origin/main` перед интеграцией', 'Локальная `main` уже ушла вперёд, но данные об `origin/main` могут быть устаревшими. Сначала сделай `fetch`, а уже потом думай про `pull`.', 'INTERMEDIATE', '["remote","inspection","planning"]'::jsonb, '{"status":"db-seeded","goal":"Сначала обновите remote-tracking refs и только после этого решайте, нужен ли `pull`, `merge` или `rebase`.","instructions":[{"position":1,"id":"refresh-remote-state-before-integration","text":"Не интегрируйте удалённые коммиты сразу. Первый шаг здесь — отдельный `fetch`."},{"position":2,"id":"treat-local-ahead-and-remote-behind-as-incomplete-view","text":"Задача не про `pull`; она про получение актуального состояния `origin/main`."},{"position":3,"id":"keep-next-step-in-preview-mode","text":"После команды локальная история не должна смешаться с удалённой: сначала только обновите refs."}],"steps":[{"position":1,"title":"Заметьте, что данные об `origin/main` могут устареть","detail":"По текущему контексту видно расхождение, но пока нет гарантии, что локальная картина удалённой ветки свежая."},{"position":2,"title":"Обновите remote-tracking refs","detail":"Сделайте безопасный шаг, который получит свежие данные с удалённого репозитория без интеграции в локальную ветку."},{"position":3,"title":"Отделите fetch от merge","detail":"После `fetch` уже можно будет обсуждать интеграцию, но не раньше."},{"position":4,"title":"Оставьте решение о pull на следующий шаг","detail":"Этот сценарий заканчивается сразу после обновления удалённого состояния."}],"annotations":[{"position":1,"label":"Что проверяем","message":"Сначала получаем свежие remote refs, затем уже оцениваем divergence."},{"position":2,"label":"Какой шаг ожидается","message":"Правильный ответ — команда из семейства `git fetch`, без `pull`, `merge` и `rebase`."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"main","current":true},{"name":"origin/main","current":false}],"commits":[{"id":"87d20aa","summary":"docs: уточнить чеклист синхронизации"},{"id":"3fd81e5","summary":"feat: подготовить баннер статуса удалённого репозитория"}],"files":[{"path":"docs/sync-playbook.md","status":"clean"},{"path":"frontend/src/banner.js","status":"clean"}],"annotations":[{"label":"Сигнал неполной картины","message":"Локальная `main` уже опережает известный `origin/main`, но на удалённом есть ещё не полученные изменения."},{"label":"Почему `pull` пока рано","message":"`pull` смешивает получение новых данных и интеграцию. Сначала нужен отдельный `fetch`."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('stash-checkpoint-draft', 'stash-checkpoint-draft', 'default', 'db-seeded', 'Убери черновик в stash перед переключением', 'В `feature/stash-panel-draft` изменён `frontend/src/demo-panel.js` и появился новый `notes/ui-placeholder.txt`. Сначала проверь статус, затем сохрани всё в stash вместе с untracked-файлом.', 'BEGINNER', '["stash","working-tree","safety"]'::jsonb, '{"status":"db-seeded","goal":"Нужно подтвердить, что в ветке есть и changed, и untracked файлы, а затем убрать их в stash так, чтобы рабочее дерево стало чистым.","instructions":[{"position":1,"id":"inspect-dirty-worktree-before-stash","text":"Сначала убедитесь, что в `feature/stash-panel-draft` есть и изменённый tracked-файл, и новый untracked-файл."},{"position":2,"id":"include-untracked-files-in-checkpoint","text":"Stash должен забрать не только `frontend/src/demo-panel.js`, но и `notes/ui-placeholder.txt`."},{"position":3,"id":"leave-branch-ready-for-next-step","text":"После stash рабочее дерево должно стать чистым, чтобы ветку можно было безопасно переключать или продолжать позже."}],"steps":[{"position":1,"title":"Проверьте текущее грязное состояние","detail":"Перед stash зафиксируйте, что в репозитории есть и modified, и untracked изменения."},{"position":2,"title":"Сохраните всё в stash","detail":"Выберите такую команду, которая уберёт и tracked, и untracked файлы в один checkpoint."},{"position":3,"title":"Оставьте ветку чистой","detail":"После stash локальный шум должен исчезнуть, а изменения остаться доступными для возврата позже."}],"annotations":[{"position":1,"label":"Что проверяем","message":"Обычный просмотр статуса допустим как промежуточный шаг, но задача завершается только после stash."},{"position":2,"label":"Какой результат нужен","message":"Нужно убрать в stash и изменённый файл, и новый untracked-файл, чтобы рабочее дерево стало чистым."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"feature/stash-panel-draft","current":true},{"name":"main","current":false}],"commits":[{"id":"5d91af0","summary":"draft: добавить временный контент для панели"},{"id":"88ce113","summary":"ui: подготовить черновой блок навигации"}],"files":[{"path":"frontend/src/demo-panel.js","status":"modified"},{"path":"notes/ui-placeholder.txt","status":"untracked"}],"annotations":[{"label":"Что лежит в рабочем дереве","message":"`frontend/src/demo-panel.js` уже изменён, а `notes/ui-placeholder.txt` существует только локально и тоже не должен потеряться."},{"label":"Безопасный следующий шаг","message":"Сначала подтвердите статус, затем сохраните tracked и untracked изменения в stash."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('merge-sandbox-outline', 'merge-sandbox-outline', 'default', 'db-seeded', 'Сравни diff перед попыткой merge', 'Вы на `feature/mock-merge-window` с незавершёнными правками. Перед merge безопасно посмотреть diff с `main` или общий граф веток, а не запускать слияние сразу.', 'INTERMEDIATE', '["branching","history","planning"]'::jsonb, '{"status":"db-seeded","goal":"Нужно понять, чем `feature/mock-merge-window` отличается от `main`, и сделать это через preview-команду, не выполняя merge.","instructions":[{"position":1,"id":"inspect-merge-shape","text":"Сначала подтвердите контекст ветки, а затем откройте preview различий или истории."},{"position":2,"id":"stay-in-preview-mode","text":"Задача заканчивается на просмотре diff или графа. Никакого `git merge` здесь выполнять не нужно."},{"position":3,"id":"use-preview-copy","text":"Подойдёт команда, которая либо показывает diff между `main` и `feature/mock-merge-window`, либо строит понятный граф веток."}],"steps":[{"position":1,"title":"Подтвердите текущую ветку","detail":"Сначала зафиксируйте, что вы на `feature/mock-merge-window`, а не на `main` или `release/demo`."},{"position":2,"title":"Сравните feature с `main`","detail":"Посмотрите, какие изменения накопились перед потенциальным merge, и не трогайте историю."},{"position":3,"title":"Выберите diff или граф","detail":"Правильный ответ — безопасный preview: либо различия, либо граф веток."},{"position":4,"title":"Оставьте merge на следующий шаг","detail":"После preview уже можно обсуждать слияние, но этот сценарий останавливается раньше."}],"annotations":[{"position":1,"label":"Что проверяем","message":"Сначала нужно увидеть форму расхождения между `main` и `feature/mock-merge-window`, не меняя репозиторий."},{"position":2,"label":"Какой шаг ожидается","message":"Подойдёт `git diff main...feature/mock-merge-window` или просмотр полного графа веток."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"feature/mock-merge-window","current":true},{"name":"main","current":false},{"name":"release/demo","current":false}],"commits":[{"id":"fbe4309","summary":"draft: набросать черновик preview перед merge"},{"id":"2cc9b15","summary":"feat: добавить условный баннер синхронизации"}],"files":[{"path":"frontend/src/merge-banner.js","status":"modified"},{"path":"docs/mock-merge-plan.md","status":"modified"}],"annotations":[{"label":"Что видно в репозитории","message":"Активна `feature/mock-merge-window`, рядом есть `main` и `release/demo`, а в рабочем дереве уже лежат незавершённые изменения."},{"label":"Почему merge пока рано","message":"Без предварительного diff или графа вы не понимаете ни объём отличий, ни форму истории перед слиянием."}]}'::jsonb, TRUE);

INSERT INTO authored_scenarios (scenario_slug, scenario_id, source_key, source_name, title, summary, difficulty, tags_json, task_payload, repository_context_payload, enabled)
VALUES ('tag-checkpoint-preview', 'tag-checkpoint-preview', 'default', 'db-seeded', 'Проверь релизные теги перед выбором точки', 'История чистая, но в репозитории уже есть `release/demo-v1` и `checkpoint/ui-shell`. Сначала посмотри список тегов, а не создавай новый.', 'BEGINNER', '["navigation","inspection","remote"]'::jsonb, '{"status":"db-seeded","goal":"Нужно безопасно увидеть существующие теги и выбрать ориентир для релизной точки, не меняя историю.","instructions":[{"position":1,"id":"inspect-tag-list","text":"Рабочее дерево чистое, поэтому задача не про правки, а про чтение уже существующих тегов."},{"position":2,"id":"keep-copy-light","text":"Команда должна показать, какие теги уже есть в репозитории: `release/demo-v1` и `checkpoint/ui-shell`."},{"position":3,"id":"prefer-read-only-command","text":"Не создавайте и не перемещайте теги. Сначала просто просмотрите список."}],"steps":[{"position":1,"title":"Убедитесь, что история чистая","detail":"Здесь не нужно сохранять изменения или переключать ветки: задача целиком про чтение ориентиров."},{"position":2,"title":"Посмотрите существующие теги","detail":"Нужно явно увидеть, какие release/checkpoint-теги уже привязаны к истории."},{"position":3,"title":"Выберите безопасный просмотр","detail":"Подойдёт read-only команда вроде `git tag --list` или `git show-ref --tags`."}],"annotations":[{"position":1,"label":"Что проверяем","message":"Сценарий про выбор существующей контрольной точки, а не про создание нового тега."},{"position":2,"label":"Какой шаг ожидается","message":"Правильный ответ — безопасная команда просмотра списка тегов или tag refs."}]}'::jsonb, '{"status":"db-seeded","branches":[{"name":"main","current":true},{"name":"origin/main","current":false}],"commits":[{"id":"11b7d31","summary":"draft: добавить условный тег релизного ориентира"},{"id":"d34aa0c","summary":"docs: обновить заметки по контрольным точкам"}],"files":[{"path":"docs/release-tags.md","status":"clean"},{"path":"frontend/src/tag-chip.js","status":"clean"}],"annotations":[{"label":"Что уже есть в истории","message":"Рабочее дерево чистое, а в истории уже подготовлены как минимум два тега: `release/demo-v1` и `checkpoint/ui-shell`."},{"label":"Почему не нужно создавать тег сразу","message":"Сначала надо понять, какие ориентиры уже существуют, и только потом решать, нужен ли новый тег."}]}'::jsonb, TRUE);

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('status-basics', 1, 'command_text', 'git status', 'git status', 'partial', 'working-tree-inspected', 'Рабочее дерево просмотрено. Теперь можно выбрать более компактный статус.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('status-basics', 2, 'command_text', 'git status --short', 'git status --short', 'correct', 'expected-command', 'Краткий статус корректно показывает tracked и untracked изменения.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('status-basics', 3, 'command_text', 'git status -sb', 'git status -sb', 'correct', 'expected-command', 'Краткий статус корректно показывает tracked и untracked изменения.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('branch-safety', 1, 'command_text', 'git branch --show-current', 'git branch --show-current', 'partial', 'branch-context-confirmed', 'Активная ветка подтверждена. Теперь соберите компактный статус незавершённых правок.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('branch-safety', 2, 'command_text', 'git status -sb', 'git status -sb', 'correct', 'expected-command', 'Активная ветка и незавершённые правки подтверждены безопасными командами чтения.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('branch-safety', 3, 'command_text', 'git status --short -b', 'git status --short -b', 'correct', 'expected-command', 'Активная ветка и незавершённые правки подтверждены безопасными командами чтения.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('history-cleanup-preview', 1, 'command_text', 'git log --oneline --decorate', 'git log --oneline --decorate', 'partial', 'history-preview-opened', 'История просмотрена. Теперь можно открыть более наглядный граф перед cleanup.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('history-cleanup-preview', 2, 'command_text', 'git log --oneline --graph --decorate', 'git log --oneline --graph --decorate', 'correct', 'expected-command', 'Компактный граф истории показал fixup и WIP-сигналы без переписывания коммитов.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('history-cleanup-preview', 3, 'command_text', 'git log --graph --oneline --decorate', 'git log --graph --oneline --decorate', 'correct', 'expected-command', 'Компактный граф истории показал fixup и WIP-сигналы без переписывания коммитов.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('remote-sync-preview', 1, 'command_text', 'git fetch', 'git fetch', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('remote-sync-preview', 2, 'command_text', 'git fetch origin', 'git fetch origin', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('remote-sync-preview', 3, 'command_text', 'git fetch --all --prune', 'git fetch --all --prune', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('stash-checkpoint-draft', 1, 'command_text', 'git status -sb', 'git status -sb', 'partial', 'workspace-inspected', 'Контекст подтверждён, теперь сохраните текущие изменения в stash.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('stash-checkpoint-draft', 2, 'command_text', 'git status --short', 'git status --short', 'partial', 'workspace-inspected', 'Контекст подтверждён, теперь сохраните текущие изменения в stash.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('stash-checkpoint-draft', 3, 'command_text', 'git stash push -u', 'git stash push -u', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('stash-checkpoint-draft', 4, 'command_text', 'git stash push --include-untracked', 'git stash push --include-untracked', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('stash-checkpoint-draft', 5, 'command_text', 'git stash push -u -m "ui-draft"', 'git stash push -u -m "ui-draft"', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('merge-sandbox-outline', 1, 'command_text', 'git status -sb', 'git status -sb', 'partial', 'merge-context-confirmed', 'Контекст ветки просмотрен. Теперь можно безопасно открыть diff или граф.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('merge-sandbox-outline', 2, 'command_text', 'git diff main...feature/mock-merge-window', 'git diff main...feature/mock-merge-window', 'correct', 'expected-command', 'Preview различий собран без запуска merge.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('merge-sandbox-outline', 3, 'command_text', 'git log --oneline --graph --decorate --all', 'git log --oneline --graph --decorate --all', 'correct', 'expected-command', 'Граф веток просмотрен без запуска merge.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('tag-checkpoint-preview', 1, 'command_text', 'git tag --list', 'git tag --list', 'correct', 'expected-command', 'Список тегов просмотрен без изменения истории.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('tag-checkpoint-preview', 2, 'command_text', 'git tag -l', 'git tag -l', 'correct', 'expected-command', 'Список тегов просмотрен без изменения истории.');

INSERT INTO authored_scenario_answers (scenario_slug, position, answer_type, raw_answer_value, normalized_answer_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('tag-checkpoint-preview', 3, 'command_text', 'git show-ref --tags', 'git show-ref --tags', 'correct', 'expected-command', 'Ссылки на теги просмотрены без изменения истории.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:status-basics:command_text', 'status-basics', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"main","workingTreeClean":false},"workspaceTemplate":{"initialBranch":"main","currentBranch":"main","branches":["docs/review-notes"],"committedFiles":[{"path":"README.md","content":"# Git Trainer\n"},{"path":"src/main.js","content":"export const workspaceShell = ''stable'';\n"}],"modifiedFiles":[{"path":"README.md","content":"# Git Trainer\n\n- review draft\n"},{"path":"src/main.js","content":"export const workspaceShell = ''noisy'';\n"}],"untrackedFiles":[{"path":"notes/status-checklist.md","content":"- inspect modified files\n"}]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:status-basics:command_text', 1, 'exact_normalized_command', 'git status', 'git status', 'partial', 'working-tree-inspected', 'Рабочее дерево просмотрено. Теперь можно выбрать более компактный статус.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:status-basics:command_text', 2, 'exact_normalized_command', 'git status --short', 'git status --short', 'correct', 'expected-command', 'Краткий статус корректно показывает tracked и untracked изменения.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:status-basics:command_text', 3, 'exact_normalized_command', 'git status -sb', 'git status -sb', 'correct', 'expected-command', 'Краткий статус корректно показывает tracked и untracked изменения.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:branch-safety:command_text', 'branch-safety', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"release/hotfix-7","workingTreeClean":false},"requiredPriorCommandsByCommand":{"git status -sb":["git branch --show-current"],"git status --short -b":["git branch --show-current"]},"workspaceTemplate":{"initialBranch":"main","currentBranch":"release/hotfix-7","branches":["release/hotfix-7","feature/menu-refresh","main"],"committedFiles":[{"path":"src/ui/header.css","content":".header { padding: 8px; }\n"},{"path":"docs/release-checklist.md","content":"- verify deploy\n"}],"modifiedFiles":[{"path":"src/ui/header.css","content":".header { padding: 12px; }\n"},{"path":"docs/release-checklist.md","content":"- verify deploy\n- smoke test\n"}],"untrackedFiles":[]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:branch-safety:command_text', 1, 'exact_normalized_command', 'git branch --show-current', 'git branch --show-current', 'partial', 'branch-context-confirmed', 'Активная ветка подтверждена. Теперь соберите компактный статус незавершённых правок.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:branch-safety:command_text', 2, 'exact_normalized_command', 'git status -sb', 'git status -sb', 'correct', 'expected-command', 'Активная ветка и незавершённые правки подтверждены безопасными командами чтения.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:branch-safety:command_text', 3, 'exact_normalized_command', 'git status --short -b', 'git status --short -b', 'correct', 'expected-command', 'Активная ветка и незавершённые правки подтверждены безопасными командами чтения.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:history-cleanup-preview:command_text', 'history-cleanup-preview', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"feature/history-cleanup","workingTreeClean":false},"workspaceTemplate":{"initialBranch":"main","currentBranch":"feature/history-cleanup","branches":["feature/history-cleanup","main"],"committedFiles":[{"path":"frontend/src/styles.css","content":".badge { padding: 4px; }\n"},{"path":"frontend/src/workspace-shell/view.js","content":"export const badge = ''shell'';\n"}],"modifiedFiles":[{"path":"frontend/src/styles.css","content":".badge { padding: 6px; }\n"},{"path":"frontend/src/workspace-shell/view.js","content":"export const badge = ''shell-preview'';\n"}],"untrackedFiles":[]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:history-cleanup-preview:command_text', 1, 'exact_normalized_command', 'git log --oneline --decorate', 'git log --oneline --decorate', 'partial', 'history-preview-opened', 'История просмотрена. Теперь можно открыть более наглядный граф перед cleanup.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:history-cleanup-preview:command_text', 2, 'exact_normalized_command', 'git log --oneline --graph --decorate', 'git log --oneline --graph --decorate', 'correct', 'expected-command', 'Компактный граф истории показал fixup и WIP-сигналы без переписывания коммитов.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:history-cleanup-preview:command_text', 3, 'exact_normalized_command', 'git log --graph --oneline --decorate', 'git log --graph --oneline --decorate', 'correct', 'expected-command', 'Компактный граф истории показал fixup и WIP-сигналы без переписывания коммитов.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:remote-sync-preview:command_text', 'remote-sync-preview', 'command_text', 'git_repo_state_probe', 5000, '{"expectedExitCode":0,"workspaceTemplate":{"initialBranch":"main","remoteName":"origin","localAheadCommitMessage":"local notes WIP","remoteAheadCommitMessage":"remote hotfix ready","baseFiles":[{"path":"README.md","content":"# Git Trainer\n"},{"path":"docs/sync-playbook.md","content":"- inspect divergence\n"}],"localAheadFiles":[{"path":"docs/local-notes.md","content":"- pending local integration\n"}],"remoteAheadFiles":[{"path":"release/remote-hotfix.md","content":"- hotfix available upstream\n"}]},"expectedState":{"currentBranch":"main","localHeadCommitMessage":"local notes WIP","fetchHeadCommitMessage":"remote hotfix ready","remoteTrackingRefs":[{"ref":"refs/remotes/origin/main","commitMessage":"remote hotfix ready"}]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:remote-sync-preview:command_text', 1, 'exact_normalized_command', 'git fetch', 'git fetch', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:remote-sync-preview:command_text', 2, 'exact_normalized_command', 'git fetch origin', 'git fetch origin', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:remote-sync-preview:command_text', 3, 'exact_normalized_command', 'git fetch --all --prune', 'git fetch --all --prune', 'correct', 'expected-command', 'Удалённое состояние обновлено отдельно от интеграции.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:stash-checkpoint-draft:command_text', 'stash-checkpoint-draft', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"feature/stash-panel-draft","workingTreeClean":true,"stashEntryCount":1},"workspaceTemplate":{"initialBranch":"main","currentBranch":"feature/stash-panel-draft","branches":["feature/stash-panel-draft","main"],"committedFiles":[{"path":"frontend/src/demo-panel.js","content":"export const panel = ''draft'';\n"}],"modifiedFiles":[{"path":"frontend/src/demo-panel.js","content":"export const panel = ''draft-staged'';\n"}],"untrackedFiles":[{"path":"notes/ui-placeholder.txt","content":"temporary ui notes\n"}]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:stash-checkpoint-draft:command_text', 1, 'exact_normalized_command', 'git status -sb', 'git status -sb', 'partial', 'workspace-inspected', 'Контекст подтверждён, теперь сохраните текущие изменения в stash.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:stash-checkpoint-draft:command_text', 2, 'exact_normalized_command', 'git status --short', 'git status --short', 'partial', 'workspace-inspected', 'Контекст подтверждён, теперь сохраните текущие изменения в stash.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:stash-checkpoint-draft:command_text', 3, 'exact_normalized_command', 'git stash push -u', 'git stash push -u', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:stash-checkpoint-draft:command_text', 4, 'exact_normalized_command', 'git stash push --include-untracked', 'git stash push --include-untracked', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:stash-checkpoint-draft:command_text', 5, 'exact_normalized_command', 'git stash push -u -m "ui-draft"', 'git stash push -u -m "ui-draft"', 'correct', 'expected-command', 'Изменения и untracked-файлы безопасно убраны в stash.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:merge-sandbox-outline:command_text', 'merge-sandbox-outline', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"feature/mock-merge-window","workingTreeClean":false},"workspaceTemplate":{"initialBranch":"main","currentBranch":"feature/mock-merge-window","branches":["feature/mock-merge-window","release/demo","main"],"committedFiles":[{"path":"frontend/src/merge-banner.js","content":"export const mergeBanner = ''draft'';\n"},{"path":"docs/mock-merge-plan.md","content":"- inspect merge shape\n"}],"modifiedFiles":[{"path":"frontend/src/merge-banner.js","content":"export const mergeBanner = ''outline'';\n"},{"path":"docs/mock-merge-plan.md","content":"- inspect merge shape\n- review diff\n"}],"untrackedFiles":[]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:merge-sandbox-outline:command_text', 1, 'exact_normalized_command', 'git status -sb', 'git status -sb', 'partial', 'merge-context-confirmed', 'Контекст ветки просмотрен. Теперь можно безопасно открыть diff или граф.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:merge-sandbox-outline:command_text', 2, 'exact_normalized_command', 'git diff main...feature/mock-merge-window', 'git diff main...feature/mock-merge-window', 'correct', 'expected-command', 'Preview различий собран без запуска merge.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:merge-sandbox-outline:command_text', 3, 'exact_normalized_command', 'git log --oneline --graph --decorate --all', 'git log --oneline --graph --decorate --all', 'correct', 'expected-command', 'Граф веток просмотрен без запуска merge.');

INSERT INTO authored_scenario_validator_specs (validator_spec_id, scenario_slug, answer_type, validator_type, timeout_ms, config_payload, enabled)
VALUES ('default:tag-checkpoint-preview:command_text', 'tag-checkpoint-preview', 'command_text', 'git_command_probe', 5000, '{"expectedExitCode":0,"expectedWorkspaceState":{"currentBranch":"main","workingTreeClean":true,"tagCount":2},"workspaceTemplate":{"initialBranch":"main","currentBranch":"main","branches":[],"committedFiles":[{"path":"docs/release-tags.md","content":"- release/demo-v1\n"},{"path":"frontend/src/tag-chip.js","content":"export const checkpoint = ''demo'';\n"}],"modifiedFiles":[],"untrackedFiles":[],"tags":["release/demo-v1","checkpoint/ui-shell"]}}'::jsonb, TRUE);

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:tag-checkpoint-preview:command_text', 1, 'exact_normalized_command', 'git tag --list', 'git tag --list', 'correct', 'expected-command', 'Список тегов просмотрен без изменения истории.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:tag-checkpoint-preview:command_text', 2, 'exact_normalized_command', 'git tag -l', 'git tag -l', 'correct', 'expected-command', 'Список тегов просмотрен без изменения истории.');

INSERT INTO authored_scenario_validator_rules (validator_spec_id, position, match_type, raw_match_value, normalized_match_value, outcome_correctness, outcome_code, outcome_message)
VALUES ('default:tag-checkpoint-preview:command_text', 3, 'exact_normalized_command', 'git show-ref --tags', 'git show-ref --tags', 'correct', 'expected-command', 'Ссылки на теги просмотрены без изменения истории.');

INSERT INTO authored_scenario_retry_guidance (scenario_slug, incorrect_explanation_code, incorrect_focus, incorrect_hint_template_code)
VALUES ('status-basics', 'inspection-command-should-come-before-mutation', 'inspect-working-tree-before-acting', 'working-tree-inspection');

INSERT INTO authored_scenario_retry_guidance (scenario_slug, incorrect_explanation_code, incorrect_focus, incorrect_hint_template_code)
VALUES ('branch-safety', 'branch-choice-needs-task-alignment', 'compare-branch-purpose-before-switching', 'branch-intent');

INSERT INTO authored_scenario_retry_guidance (scenario_slug, incorrect_explanation_code, incorrect_focus, incorrect_hint_template_code)
VALUES ('history-cleanup-preview', 'history-cleanup-requires-plan-first', 'plan-history-cleanup-before-rewriting', 'history-plan');

INSERT INTO authored_scenario_retry_guidance (scenario_slug, incorrect_explanation_code, incorrect_focus, incorrect_hint_template_code)
VALUES ('remote-sync-preview', 'remote-sync-requires-fetch-first', 'refresh-remote-state-before-integration', 'remote-fetch');

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('partial-answer-needs-refinement', 'explanation', '{"title":"Вы смотрите в правильную область, но команду ещё нужно уточнить","tone":"partial","messageTemplate":"`{{submittedAnswer}}` указывает на правильный сигнал репозитория, но задаче всё ещё нужна более точная команда проверки, прежде чем ответ станет правильным.","details":["Пользователь уже стартовал из правильного семейства команд проверки, поэтому сообщение о повторе должно поддержать это направление, а не считать ответ полным промахом.","Следующая подсказка может сузить форму команды, не меняя саму панель обратной связи."]}'::jsonb);

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('unsupported-answer-type', 'explanation', '{"title":"Вернитесь к поддерживаемому вводу команды","tone":"unsupported","messageTemplate":"Сейчас проверяются только ответы в виде команды, поэтому перед следующей попыткой нужно вернуть поддерживаемый формат.","details":["Запрос принимается, но такой тип ответа всё ещё считается неподдерживаемым.","Панель повтора должна сначала вернуть пользователя к поддерживаемому командному формату, а уже потом пробовать более богатые варианты ответа."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('branch-choice-needs-task-alignment', 'explanation', '{"title":"Подтвердите текущую ветку до решения о переключении","tone":"incorrect","messageTemplate":"В этом сценарии безопасный следующий шаг — сначала прочитать активную ветку или branch-aware status, потому что репозиторий уже содержит незавершённые hotfix-изменения. Переключение прямо сейчас оставалось бы догадкой.","details":["Сценарий пока не просит выполнять `checkout`. Сначала он требует собрать минимальный branch cue и подтвердить, где уже открыта работа.","После такой проверки пользователь сможет аргументированно решить, допустимо ли переключение, не смешивая hotfix и feature-контекст."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('history-cleanup-requires-plan-first', 'explanation', '{"title":"Сначала просмотрите историю, потом переписывайте коммиты","tone":"incorrect","messageTemplate":"В этом сценарии следующий безопасный шаг — сначала показать недавний стек истории в читаемом виде, потому что `fixup!` и WIP-сигналы ещё нужно явно увидеть до любого `rebase`.","details":["Правильная следующая попытка остаётся в семействе `git log` и помогает увидеть, какие коммиты вообще войдут в cleanup.","Только после такого preview можно аргументированно обсуждать interactive rebase или другую команду переписывания."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('inspection-command-should-come-before-mutation', 'explanation', '{"title":"Проверьте рабочее дерево до любых изменений","tone":"incorrect","messageTemplate":"Безопасное следующее действие в этом сценарии — сначала проверить состояние репозитория, а не сразу переходить к изменяющей команде.","details":["Это упражнение про чтение текущего состояния до действия, а не про выбор целевой ветки или изменение файлов.","Панель повтора должна удерживать пользователя в цикле проверки, пока форма правильной команды не станет очевидной."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('remote-sync-requires-fetch-first', 'explanation', '{"title":"Сначала обновите удалённое состояние, потом интегрируйте","tone":"incorrect","messageTemplate":"В этом сценарии безопасный следующий шаг — отдельно получить новые remote refs, потому что без свежего `fetch` решение о `pull` или другой интеграции остаётся преждевременным.","details":["Правильная следующая попытка должна оставаться в семействе `git fetch` и обновить наблюдаемое состояние `origin/main` без слияния.","Только после такого preview можно предметно решать, нужен ли `pull`, `merge` или `rebase`."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('retry-guidance-needs-scenario-review', 'explanation', '{"title":"Вернитесь к цели сценария перед следующей попыткой","tone":"incorrect","messageTemplate":"Цикл повтора должен вернуть пользователя к цели сценария, а затем сузить следующую попытку самым маленьким доступным безопасным намёком.","details":["Когда сценарно-специфичная подсказка недоступна, объяснение должно оставаться сфокусированным на цели задачи, а не изобретать новые правила.","Следующая подсказка всё ещё может сузить путь повтора, не затрагивая слой policy."]}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('partial-answer', 'hint', '{"nudgeTitle":"Останьтесь в том же семействе проверок","nudgeMessage":"Оставайтесь в той же зоне проверки, но уберите лишний охват или переключитесь на каноничную безопасную команду для сценария.","strongTitle":"Сверьтесь с точным безопасным шагом","strongMessage":"Ищите самую маленькую команду, которая проверяет именно то состояние репозитория, о котором спрашивает задача, без лишнего намерения."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('unsupported-answer-type', 'hint', '{"nudgeTitle":"Используйте режим текста команды","nudgeMessage":"Переключите тип ответа обратно на текст команды и оставьте следующую попытку в форме простой команды проверки.","strongTitle":"Ориентируйтесь на поддерживаемый пример","strongMessage":"Посмотрите на бейдж поддерживаемого типа ответа над формой и сначала вернитесь к этому режиму."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('branch-intent', 'hint', '{"nudgeTitle":"Сначала подтвердите активную ветку","nudgeMessage":"Выберите branch-reading шаг, который ничего не меняет в репозитории, но явно показывает, где сейчас открыта работа.","strongTitle":"Выберите команду чтения branch-контекста","strongMessage":"Нужна самая маленькая команда из семейства `git branch --show-current` или branch-aware `git status`, которая подтверждает текущую ветку до любых решений о `checkout`."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('history-plan', 'hint', '{"nudgeTitle":"Сначала покажите компактную историю","nudgeMessage":"Оставайтесь в preview-режиме и выберите команду, которая показывает верхушку истории с `fixup!` и WIP, не меняя коммиты.","strongTitle":"Выберите команду просмотра графа истории","strongMessage":"Нужна компактная команда из семейства `git log --oneline --decorate`; вариант с `--graph` тоже подходит, если делает стек читаемее."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('working-tree-inspection', 'hint', '{"nudgeTitle":"Начните с проверки рабочего дерева","nudgeMessage":"Сценарий спрашивает о состоянии репозитория, поэтому следующая попытка должна оставаться в семействе `git status`, а не менять файлы или ветки.","strongTitle":"Используйте `git status` как безопасный первый шаг","strongMessage":"Сначала отправьте `git status` или `git status --short`, чтобы подтвердить изменённые и неотслеживаемые файлы до любого следующего действия."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('remote-fetch', 'hint', '{"nudgeTitle":"Сначала получите свежие remote refs","nudgeMessage":"Выберите отдельный шаг получения данных с удалённого репозитория, который обновляет картину `origin/main`, но не интегрирует изменения в локальную ветку.","strongTitle":"Выберите команду из семейства `git fetch`","strongMessage":"Нужна команда вроде `git fetch` или `git fetch origin`, а не `pull`, потому что сценарий сначала оценивает обновление remote-tracking состояния."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;

INSERT INTO retry_feedback_templates (template_code, template_type, payload)
VALUES ('generic-retry', 'hint', '{"nudgeTitle":"Вернитесь к цели сценария","nudgeMessage":"Переформулируйте задачу в одном предложении и держите следующую попытку сфокусированной на самой маленькой безопасной команде, которая на неё отвечает.","strongTitle":"Покажите самый маленький безопасный следующий шаг","strongMessage":"Уберите лишнее намерение и выберите команду, которая даёт недостающий сигнал до любого более крупного действия."}'::jsonb)
ON CONFLICT (template_code) DO NOTHING;
